<?php
// $Id:

/**
 * @file
 * 
 * Visitor Info gathers information about your site visitors.
 *
 */


/**
 * Implementation of hook_init().
 *
 */

function visitorinfo_init() {
  // need to get the webservers IP so we can exclude it.
  $servers_ip = $_SERVER['SERVER_ADDR'];
  // get the visitors ip address
  $ip = ip_address();
  // exclude the webservers IP
  if ($servers_ip != $ip) { 
    // and see if it is already in the db
    $result = db_query("SELECT ip FROM {visitorinfo} v WHERE v.ip = '%s' ", $ip);
    if (db_affected_rows($result) == 0) { // not in db
      // lookup IP info using GeoIP API and stash in db
      $visitor = geoip_city($ip);
      $table = 'visitorinfo';
      $record = new stdClass();
      $record->ip = $ip;
      $record->ccode = $visitor->country_code;
      $record->cname = $visitor->country_name;
      $record->state = $visitor->region;
      $record->city = $visitor->city;
      $record->zip = $visitor->postal_code;
      $record->latitude = $visitor->latitude;
      $record->longitude = $visitor->longitude;
      drupal_write_record($table, $record);
    }
  }
}

/**
 * Implementation of hook_views_api().
 *
 * This tells drupal that there is Views integration file named 
 * module-name.views.inc 
 */
function visitorinfo_views_api() {
  // Note that you can include 'path' in this array so that your views.inc 
  // file can be stored in a different location.
  return array(
    'api' => 2.0
  );
}
